linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - goimports
    - revive
    - gosec
    - unconvert
    - goconst
    - prealloc

run:
  tests: true

issues:
  exclude-dirs:  # обновленная директива вместо skip-dirs
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
